import { EvidenceSourceType, EvidenceType, type Evidence } from "@prisma/client";
import { saveEvidence } from "@/src/actions/commercial-admin";
import type { RelationOption } from "./research-form";

type EvidenceOptions = { research: RelationOption[]; products: RelationOption[]; companies: RelationOption[]; technologies: RelationOption[]; useCases: RelationOption[]; sports: RelationOption[] };
export function EvidenceForm({ evidence, options }: { evidence?: Evidence | null; options: EvidenceOptions }) { return <form action={saveEvidence} className="grid gap-5">{evidence && <input type="hidden" name="id" value={evidence.id} />}<Field label="Title" name="title" value={evidence?.title} /><div className="grid gap-4 sm:grid-cols-2"><EnumSelect label="Evidence type" name="evidenceType" values={Object.values(EvidenceType)} selected={evidence?.evidenceType} /><EnumSelect label="Source type" name="sourceType" values={Object.values(EvidenceSourceType)} selected={evidence?.sourceType} /><Single label="Research source" name="researchId" options={options.research} selected={evidence?.researchId} /><Single label="Product" name="productId" options={options.products} selected={evidence?.productId} /><Single label="Company" name="companyId" options={options.companies} selected={evidence?.companyId} /><Single label="Technology" name="technologyId" options={options.technologies} selected={evidence?.technologyId} /><Single label="Use case" name="useCaseId" options={options.useCases} selected={evidence?.useCaseId} /><Single label="Sport" name="sportId" options={options.sports} selected={evidence?.sportId} /><Field label="Source URL" name="sourceUrl" type="url" value={evidence?.sourceUrl} required={false} /><Field label="Publication year" name="publicationYear" type="number" value={evidence?.publicationYear?.toString()} required={false} /><Field label="Metric" name="metric" value={evidence?.metric} required={false} /><Field label="Population" name="population" value={evidence?.population} required={false} /><Field label="Sample size" name="sampleSize" type="number" value={evidence?.sampleSize?.toString()} required={false} /></div><Area label="Summary" name="summary" value={evidence?.summary} /><Area label="Structured finding" name="finding" value={evidence?.finding} /><p className="text-caption text-text-tertiary">Every evidence record must link to Research or a traceable source URL. Vendor-reported records must remain explicitly labelled.</p><button className="w-fit rounded-md bg-text-primary px-4 py-2 text-caption font-semibold text-bg">Save evidence</button></form>; }
function Field({ label, name, value, type = "text", required = true }: { label: string; name: string; value?: string | null; type?: string; required?: boolean }) { return <label className="grid gap-1 text-caption text-text-secondary">{label}<input name={name} type={type} required={required} defaultValue={value ?? ""} className="rounded-md border border-border bg-bg px-3 py-2 text-body text-text-primary" /></label>; }
function Area({ label, name, value }: { label: string; name: string; value?: string | null }) { return <label className="grid gap-1 text-caption text-text-secondary">{label}<textarea name={name} rows={5} defaultValue={value ?? ""} className="rounded-md border border-border bg-bg px-3 py-2 text-body text-text-primary" /></label>; }
function EnumSelect({ label, name, values, selected }: { label: string; name: string; values: string[]; selected?: string }) { return <label className="grid gap-1 text-caption text-text-secondary">{label}<select name={name} defaultValue={selected} className="rounded-md border border-border bg-bg px-3 py-2">{values.map((item) => <option key={item}>{item}</option>)}</select></label>; }
function Single({ label, name, options, selected }: { label: string; name: string; options: RelationOption[]; selected?: string | null }) { return <label className="grid gap-1 text-caption text-text-secondary">{label}<select name={name} defaultValue={selected ?? ""} className="rounded-md border border-border bg-bg px-3 py-2"><option value="">None</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
