import { ResearchStudyType, type Prisma } from "@prisma/client";
import { saveResearch } from "@/src/actions/commercial-admin";

const researchInclude = { products: true, companies: true, technologies: true, useCases: true, sports: true } satisfies Prisma.ResearchInclude;
export type AdminResearch = Prisma.ResearchGetPayload<{ include: typeof researchInclude }>;
export type RelationOption = { id: string; name: string };
export type ResearchFormOptions = { products: RelationOption[]; companies: RelationOption[]; technologies: RelationOption[]; useCases: RelationOption[]; sports: RelationOption[] };

export function ResearchForm({ research, options }: { research?: AdminResearch | null; options: ResearchFormOptions }) {
  return <form action={saveResearch} className="grid gap-5">{research && <input type="hidden" name="id" value={research.id} />}<Field label="Title" name="title" value={research?.title} /><Field label="Slug" name="slug" value={research?.slug} required={false} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Authors" name="authors" value={research?.authors} required={false} /><Field label="Journal" name="journal" value={research?.journal} required={false} /><Field label="DOI" name="doi" value={research?.doi} required={false} /><Field label="Original URL" name="url" type="url" value={research?.url} required={false} /><Field label="Publication year" name="publicationYear" type="number" value={research?.publicationYear?.toString()} required={false} /><Field label="Publication date" name="publicationDate" type="date" value={research?.publicationDate?.toISOString().slice(0, 10)} required={false} /><Field label="Population" name="population" value={research?.population} required={false} /><Field label="Sample size" name="sampleSize" type="number" value={research?.sampleSize?.toString()} required={false} /></div><label className="grid gap-1 text-caption text-text-secondary">Study type<select name="studyType" defaultValue={research?.studyType ?? "OTHER"} className="rounded-md border border-border bg-bg px-3 py-2">{Object.values(ResearchStudyType).map((item) => <option key={item}>{item}</option>)}</select></label><label className="flex items-center gap-2 text-body text-text-secondary"><input type="checkbox" name="isPeerReviewed" defaultChecked={research?.isPeerReviewed} />Peer reviewed</label><Area label="Abstract" name="abstract" value={research?.abstract} /><Area label="Structured summary" name="summary" value={research?.summary} /><div className="grid gap-5 sm:grid-cols-2"><Multi label="Products" name="productIds" options={options.products} selected={research?.products.map((item) => item.productId)} /><Multi label="Companies" name="companyIds" options={options.companies} selected={research?.companies.map((item) => item.companyId)} /><Multi label="Technologies" name="technologyIds" options={options.technologies} selected={research?.technologies.map((item) => item.technologyId)} /><Multi label="Use cases" name="useCaseIds" options={options.useCases} selected={research?.useCases.map((item) => item.useCaseId)} /><Multi label="Sports" name="sportIds" options={options.sports} selected={research?.sports.map((item) => item.sportId)} /></div><button className="w-fit rounded-md bg-text-primary px-4 py-2 text-caption font-semibold text-bg">Save research</button></form>;
}
function Field({ label, name, value, type = "text", required = true }: { label: string; name: string; value?: string | null; type?: string; required?: boolean }) { return <label className="grid gap-1 text-caption text-text-secondary">{label}<input name={name} type={type} required={required} defaultValue={value ?? ""} className="rounded-md border border-border bg-bg px-3 py-2 text-body text-text-primary" /></label>; }
function Area({ label, name, value }: { label: string; name: string; value?: string | null }) { return <label className="grid gap-1 text-caption text-text-secondary">{label}<textarea name={name} rows={6} defaultValue={value ?? ""} className="rounded-md border border-border bg-bg px-3 py-2 text-body text-text-primary" /></label>; }
function Multi({ label, name, options, selected = [] }: { label: string; name: string; options: RelationOption[]; selected?: string[] }) { return <label className="grid gap-1 text-caption text-text-secondary">{label}<select name={name} multiple size={Math.min(6, Math.max(3, options.length))} defaultValue={selected} className="rounded-md border border-border bg-bg px-3 py-2">{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>; }
