import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { submitCompanyClaim } from "@/src/actions/vendor";
import { getCurrentUserProfile } from "@/src/lib/auth";
import { prisma } from "@/src/lib/prisma";
import { getCompanyClaimState } from "@/src/lib/vendor";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Claim Company Profile", robots: { index: false, follow: false } };
type Props = { params: Promise<{ slug: string }>; searchParams: Promise<{ submitted?: string }> };
export default async function ClaimCompanyPage({ params, searchParams }: Props) { const company = await prisma.company.findUnique({ where: { slug: (await params).slug } }); if (!company) notFound(); const user = await getCurrentUserProfile(); const state = await getCompanyClaimState(company.id, user?.id); const submitted = (await searchParams).submitted === "true"; return <main className="mx-auto min-h-[70vh] max-w-2xl px-4 py-12"><Link href={`/companies/${company.slug}`} className="text-caption font-semibold text-accent">← {company.name}</Link><p className="overline mt-6">Vendor verification</p><h1 className="mt-2 text-h1 text-text-primary">Claim {company.name}</h1><p className="mt-3 text-body-lg text-text-secondary">Claims are manually reviewed. Verification confirms company identity; it does not validate scientific claims or product effectiveness.</p>{submitted || state.claim?.status === "PENDING" ? <Status title="Claim pending review" description="An administrator will review your work email, role and request before granting access." /> : state.claim?.status === "APPROVED" ? <Status title="Claim approved" description="You can now manage this profile from the Vendor Dashboard." href="/vendor" /> : state.isClaimed ? <Status title="This profile is already managed" description="Contact the company administrator or platform support if you need access." /> : <form action={submitCompanyClaim} className="mt-8 grid gap-4 rounded-lg border border-border bg-bg-card p-6"><input type="hidden" name="companyId" value={company.id} /><input type="hidden" name="companySlug" value={company.slug} /><Field label="Work email" name="workEmail" type="email" defaultValue={user?.email ?? ""} /><Field label="Role / job title" name="jobTitle" /><label className="grid gap-1 text-caption font-medium text-text-secondary">Why are you claiming this profile?<textarea name="message" required minLength={20} rows={6} className="rounded-md border border-border bg-bg px-3 py-2 text-body text-text-primary focus:border-accent focus:outline-none" /></label><button className="w-fit rounded-md bg-text-primary px-4 py-2 text-caption font-semibold text-bg">Submit claim for review</button></form>}</main>; }
function Field({ label, name, type = "text", defaultValue = "" }: { label: string; name: string; type?: string; defaultValue?: string }) { return <label className="grid gap-1 text-caption font-medium text-text-secondary">{label}<input name={name} type={type} required defaultValue={defaultValue} className="rounded-md border border-border bg-bg px-3 py-2 text-body text-text-primary focus:border-accent focus:outline-none" /></label>; }
function Status({ title, description, href }: { title: string; description: string; href?: string }) { return <div className="mt-8 rounded-lg border border-border bg-bg-elevated p-6"><h2 className="text-h3 text-text-primary">{title}</h2><p className="mt-2 text-body text-text-secondary">{description}</p>{href && <Link href={href} className="mt-4 inline-block text-caption font-semibold text-accent">Open Vendor Dashboard →</Link>}</div>; }
