import { submitDemoRequest } from "@/src/actions/vendor";

export function DemoRequestForm({ product, defaults }: { product: { id: string; slug: string; name: string }; defaults?: { name?: string | null; email?: string | null; organization?: string | null } }) {
  return <details className="rounded-lg border border-border bg-bg-card"><summary className="cursor-pointer px-4 py-3 text-caption font-semibold text-text-primary">Request Demo</summary><form action={submitDemoRequest} className="grid gap-4 border-t border-border p-4"><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="productSlug" value={product.slug} /><p className="text-body text-text-secondary">Connect with the verified team behind {product.name}.</p><Field label="Name" name="name" defaultValue={defaults?.name ?? ""} /><Field label="Work email" name="email" type="email" defaultValue={defaults?.email ?? ""} /><Field label="Organization" name="organization" defaultValue={defaults?.organization ?? ""} /><Field label="Role / job title" name="jobTitle" /><label className="grid gap-1 text-caption font-medium text-text-secondary">Message<textarea name="message" required minLength={10} rows={4} className="rounded-md border border-border bg-bg px-3 py-2 text-body text-text-primary focus:border-accent focus:outline-none" /></label><button className="w-fit rounded-md bg-text-primary px-4 py-2 text-caption font-semibold text-bg">Send request</button><p className="text-caption text-text-tertiary">Your details are shared only with the verified company managing this profile.</p></form></details>;
}

function Field({ label, name, type = "text", defaultValue = "" }: { label: string; name: string; type?: string; defaultValue?: string }) {
  return <label className="grid gap-1 text-caption font-medium text-text-secondary">{label}<input type={type} name={name} required defaultValue={defaultValue} className="rounded-md border border-border bg-bg px-3 py-2 text-body text-text-primary focus:border-accent focus:outline-none" /></label>;
}
