import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { formatDistanceToNow } from "date-fns";
import { unwatchCompany, unwatchProduct } from "@/src/actions/watchlist";
import { Badge } from "@/src/components/intelligence/cards";
import { getCurrentUserProfile } from "@/src/lib/auth";
import { getUserWatchlist, type WatchlistSort } from "@/src/lib/watchlist";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Your Watchlist | Sports Tech Intelligence", robots: { index: false, follow: false } };
type Props = { searchParams: Promise<{ type?: string; sort?: string }> };

export default async function WatchlistPage({ searchParams }: Props) {
  const user = await getCurrentUserProfile();
  if (!user) redirect("/sign-in?redirect_url=%2Fwatchlist");
  const params = await searchParams;
  const type = ["all", "companies", "products", "technologies"].includes(params.type ?? "") ? params.type! : "all";
  const sort: WatchlistSort = params.sort === "name" ? "name" : "recent";
  const watchlist = await getUserWatchlist(user.id, sort);
  const total = watchlist.companies.length + watchlist.products.length + watchlist.technologies.length;
  const href = (next: Record<string, string>) => { const query = new URLSearchParams({ type, sort, ...next }); if (query.get("type") === "all") query.delete("type"); if (query.get("sort") === "recent") query.delete("sort"); return `/watchlist${query.size ? `?${query}` : ""}`; };
  return <main className="min-h-screen bg-bg"><header className="border-b border-border"><div className="mx-auto max-w-content px-4 py-12 lg:px-8"><p className="overline">Monitoring</p><h1 className="mt-2 text-h1 text-text-primary">Your Watchlist</h1><p className="mt-3 text-body-lg text-text-secondary">Track companies, products and technologies that matter to you.</p></div></header><section className="mx-auto max-w-content px-4 py-8 lg:px-8">
    <div className="flex flex-col justify-between gap-4 border-b border-border pb-5 sm:flex-row sm:items-center"><nav className="flex flex-wrap gap-2" aria-label="Watchlist types">{[["all", "All"], ["companies", "Companies"], ["products", "Products"], ["technologies", "Technologies"]].map(([value, label]) => <Link key={value} href={href({ type: value })} className={`rounded-full px-3 py-1.5 text-caption font-semibold ${type === value ? "bg-text-primary text-bg" : "bg-bg-elevated text-text-secondary"}`}>{label}</Link>)}</nav><div className="flex gap-3 text-caption"><Link href={href({ sort: "recent" })} className={sort === "recent" ? "font-semibold text-accent" : "text-text-tertiary"}>Recently added</Link><Link href={href({ sort: "name" })} className={sort === "name" ? "font-semibold text-accent" : "text-text-tertiary"}>A–Z</Link></div></div>
    {!total ? <EmptyWatchlist /> : <div className="mt-8 space-y-10">{(type === "all" || type === "companies") && watchlist.companies.length > 0 && <section><h2 className="text-h2 text-text-primary">Companies</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{watchlist.companies.map(({ company, companyId, createdAt, unreadActivity }) => <article key={companyId} className="card-surface p-5"><div className="flex items-start justify-between gap-3"><div><Link href={`/companies/${company.slug}`} className="text-h3 text-text-primary hover:text-accent">{company.name}</Link><p className="mt-2 line-clamp-2 text-body text-text-secondary">{company.shortDescription ?? company.description}</p></div>{unreadActivity > 0 && <Badge>{unreadActivity} new</Badge>}</div><div className="mt-4 flex flex-wrap gap-4 text-caption text-text-tertiary"><span>{company._count.products} products</span><span>{company.articles[0] ? `Latest ${formatDistanceToNow(company.articles[0].article.publishedAt, { addSuffix: true })}` : "No linked intelligence yet"}</span><span>Watched {formatDistanceToNow(createdAt, { addSuffix: true })}</span></div><div className="mt-5 flex items-center gap-4"><Link href={`/companies/${company.slug}`} className="text-caption font-semibold text-accent">View company →</Link><form action={unwatchCompany}><input type="hidden" name="entityId" value={companyId} /><button className="text-caption text-text-tertiary hover:text-text-primary">Unwatch</button></form></div></article>)}</div></section>}
      {(type === "all" || type === "products") && watchlist.products.length > 0 && <section><h2 className="text-h2 text-text-primary">Products</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{watchlist.products.map(({ product, productId, createdAt, unreadActivity }) => <article key={productId} className="card-surface p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-caption text-accent">{product.company.name}</p><Link href={`/products/${product.slug}`} className="mt-1 block text-h3 text-text-primary hover:text-accent">{product.name}</Link><p className="mt-2 line-clamp-2 text-body text-text-secondary">{product.shortDescription ?? product.description}</p></div>{unreadActivity > 0 && <Badge>{unreadActivity} new</Badge>}</div><div className="mt-4 flex flex-wrap gap-2">{product.technologies.slice(0, 3).map(({ technology }) => <Badge key={technology.id}>{technology.name}</Badge>)}{product.useCases.slice(0, 2).map(({ useCase }) => <Badge key={useCase.id}>{useCase.name}</Badge>)}</div><p className="mt-4 text-caption text-text-tertiary">{product.articles[0] ? `Latest intelligence ${formatDistanceToNow(product.articles[0].article.publishedAt, { addSuffix: true })}` : `Watched ${formatDistanceToNow(createdAt, { addSuffix: true })}`}</p><div className="mt-5 flex items-center gap-4"><Link href={`/products/${product.slug}`} className="text-caption font-semibold text-accent">View product →</Link><form action={unwatchProduct}><input type="hidden" name="entityId" value={productId} /><button className="text-caption text-text-tertiary hover:text-text-primary">Unwatch</button></form></div></article>)}</div></section>}
      {(type === "all" || type === "technologies") && watchlist.technologies.length > 0 && <section><h2 className="text-h2 text-text-primary">Technologies</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{watchlist.technologies.map(({ technology, technologyId, unreadActivity }) => <article key={technologyId} className="card-surface p-5"><div className="flex justify-between gap-3"><h3 className="text-h3 text-text-primary">{technology.name}</h3>{unreadActivity > 0 && <Badge>{unreadActivity} new</Badge>}</div><p className="mt-2 text-body text-text-secondary">{technology.description ?? "Technology monitoring profile."}</p></article>)}</div></section>}
    </div>}
  </section></main>;
}

function EmptyWatchlist() { return <div className="mt-10 rounded-lg border border-dashed border-border px-6 py-12 text-center"><h2 className="text-h2 text-text-primary">Track the sports technology that matters to you.</h2><p className="mx-auto mt-3 max-w-xl text-body text-text-secondary">Watch companies and products to see new intelligence and important changes in one place.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Link href="/companies" className="rounded-lg bg-text-primary px-5 py-2.5 text-caption font-semibold text-bg">Explore companies</Link><Link href="/products" className="rounded-lg border border-border px-5 py-2.5 text-caption font-semibold text-text-primary">Explore products</Link></div></div>; }
